### ISSUE TITLE
Publication issue

### ISSUE THREAD

**Issue by robertpitt** [astronomerio/meteor-astronomer#12]
Hey,

Were seing an issue that we believe is being caused by master/src/publications.js#L12.

## Preface
We do not use facebook, google, twitter or github, we use a custom service called centiq which works in the same way as google but with our internal oauth provider.

## The problem
When we login, our `Meteor.user().services` object contains two sub-objects, `centiq` and `resume`, but following a hard refresh these sub-objects vanish and causes obvious errors within our application.

I believe that the issue is because caused by the fields for the publication overriding another publication somewhere else.

I can use the settings file to set `disableUserTracking` to true and the issue goes away.

Can someone look into this a little more please.

Thanks

@peterchoo, @robfallows

**Comment by ryw** [comment]
Hi Robert — we'll look at it today :)

**Comment by peterchoo** [comment]
Our accounts package is essentially a clone of the [google](https://github.com/meteor/meteor/tree/devel/packages/google) and the [accounts-google](https://github.com/meteor/meteor/tree/devel/packages/accounts-google) packages provided by the Meteor team.  We have customised them slightly to utilise our own OAuth server, and have the service registered as `centiq`.

We are currently under the impression that because both astronomer and the accounts-base package are using `Meteor.publish(null, funciton(){});` and I am doing a little bit of investigation work to see if this is an issue for Meteor myself right now, I'll keep you posted.

Thanks for looking in to it.

**Comment by schnie** [comment]
Looking into it right now as well.  Definitely looks like the publications
are clobbering each other in some way.

**Comment by schnie** [comment]
Looks like its a known issue with meteor/DDP only merging top level fields.  Looking into a workaround way to keep the data we need isolated from any application data.  I'll post back here with a fix hopefully.

**Comment by peterchoo** [comment]
@schnie Yeah, that's the conclusion I just came to as well. I'm thinking it would be best to not pollute the Meteor.users publications at all, as it's often likely a user will have a third party login service.

To that end what about creating an Astronomer.users collection which collates the required data and publishes based on `this.userId` in a similar manner.

Additionally, you can have a weak dependency check for `accounts-base` and `accounts-oauth`, and use `Accounts.oauth.serviceNames()` to retrieve a list of the currently registered OAuth services, and publish based on that?

**Comment by robertpitt** [comment]
Thanks @schnie

**Comment by schnie** [comment]
Switched to using a separate client side collection, as well as cycling through Accounts.oauth.serviceNames() when looking for emails.  If any service integration has an `email` field, it will get sent down and sent along with identify calls.  Let me know how it works out for you!

**Comment by robfallows** [comment]
Excellent news - thank you :smile:

We'll test it out and get back to you.

**Comment by robertpitt** [comment]
Can we reopen this, I have a new error and at first glance you are not depending on the meteor accounts package

```
I20150917-13:32:33.062(1)? Exception from sub id undefined ReferenceError: Accounts is not defined
I20150917-13:32:33.063(1)?     at [object Object].Package [as _handler] (packages/astronomerio:core/dist/publications.js:17:1)
I20150917-13:32:33.063(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150917-13:32:33.063(1)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150917-13:32:33.063(1)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150917-13:32:33.063(1)?     at packages/ddp/livedata_server.js:407:1
I20150917-13:32:33.063(1)?     at Array.forEach (native)
I20150917-13:32:33.063(1)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150917-13:32:33.064(1)?     at [object Object]._.extend.startUniversalSubs (packages/ddp/livedata_server.js:406:1)
I20150917-13:32:33.064(1)?     at [object Object]._.extend._setUserId (packages/ddp/livedata_server.js:744:1)
I20150917-13:32:33.064(1)?     at [object Object].setUserId [as _setUserId] (packages/ddp/livedata_server.js:634:1)
```
