### ISSUE TITLE
Ability to block specific events

### ISSUE THREAD

**Issue by markoshust** [astronomerio/meteor-astronomer#18]
I'd like to use Astronomer for a health care project, however I want to make sure personally-identifiable information isn't being sent (such as first and last names of users).

Is there a way to block specific data from being sent to Astronomer? Ideally, I'd like to define an object from multiple schemas to block.

ex.

```
block = () => {
  return [
    {
      collection_name: {
        {
          fields: {
            first_name: 1,
            last_name: 1
          }
      }
    },
    {
      another_collection: {
        {
          fields: {
            foo: 1,
            bar: 1,
            baz: 1,
          }
      }
    }
  }];
}
```

or entire collections:

```
block = () => {
  return [
    {
      collection_name,
      another_one,
      foo_bar,
    }
}
```

**Comment by schnie** [comment]
Hey @markoshust!  We currently only _automatically_ track a user's _id, and possibly an email address if we can find one on the current users document.  We also attempt to hook into iron-router and flow-router and provide super basic route tracking, as well as super basic meteor method tracking, which means we won't be sending any personal information here.  This is meant to help users get up and running sending data as quick as possible.  You can disable as many of these as you like.  This will leave event tracking up to you, giving you complete control of what data is sent.  Wherever you would like to track an event you can just drop something like this in:
`analytics.track('some health care event', { patientId: 123, doctorId: '456', somethingElse: 'blahblah' });`

Hope that helps!
