### ISSUE TITLE
Allow for Multiple DDP connections

### ISSUE THREAD

**Issue by peterchoo** [astronomerio/meteor-astronomer#19]
We have just tried to look at the frequency of some method calls, but we could not see data for any methods called on a secondary DDP connection.

As a feature request can you please extend the tracking functionality to support multiple DDP connections, maybe exposing setupMethodTracking and allowing the user to pass in a DDP connection:

https://github.com/astronomerio/meteor-astronomer/blob/master/src/tracking.js#L100-L127

Thanks

**Comment by peterchoo** [comment]
Why has this been closed?  This information would still be really useful for us.

**Comment by schnie** [comment]
Hey @peterchoo, we went went through and did a mass cleanup of our open issues across all our repos and this ended up in that bunch.

Unfortunately, we don't have the resources to support building this in at this point, and we're all pretty rusty with meteor. If you wanted to send PR, we'd happily accept it :)

Sorry for the confusion!
