### ISSUE TITLE
Normal Google Analytics (page views)

### ISSUE THREAD

**Issue by ryw** [astronomerio/meteor-astronomer#2]
Can the package also process normal Google Analytics features too?

Or do we need to tell people to add both GA + our package to their new Meteor apps?

**Comment by iDoMeteor** [comment]
I re-wrote GAnalytics package last week, after I debug the rest of my system this week I am pulling it out & packaging it up.  It is clean and reads config from a global, easy peasy.

**Comment by ryw** [comment]
Awesome, thanks @iDoMeteor — will chat w/ @schnie when he's back next week - definitely want to collaborate on this stuff :)
