### ISSUE TITLE
Astronomer and Intercom on Cordova

### ISSUE THREAD

**Issue by kylepierce** [astronomerio/meteor-astronomer#21]
I have been using astronomer for tracking and I installed the intercom cordova plugin for iOS and android. The astronomer meteor package is showing a duplicate of the messages because it attaching an iframe to the body. To solve the issue I turned off intercom on astronomer, but now I am not receiving the tracking info. 

Is there a way to prevent the iframe from attaching to the body or another way to get the data to be captured?

Ideally, it would be great to have a boolean on if the intercom iframe should be shown. I will reach out to intercom as well to see if there is a code snippet that doesnt show the iframe.

**Comment by kylepierce** [comment]
Cool...

**Comment by ryw** [comment]
Hey Kyle - sorry we closed all issues on the repo thinking they were all internally created - is this still open issue for you?
