### ISSUE TITLE
Bug: ignoreNotFoundWarning not working (src vs dist)

### ISSUE THREAD

**Issue by merlinpatt** [astronomerio/meteor-astronomer#27]
The ignoreNotFoundWarning isn't working. I believe the issue is that in my original PR, I only changed the src files and not the dist files.

I can add the change to the dist files if that's preferred. 

But I'm wondering why the dist files are there in the first place? They do not seem to be any different from src, and in most projects I've worked on, dist files are ignored.

So there are two solutions I see

1. If the src and dist files are identical, then dist should be dropped
2. If there is some difference between the two, then dist should be ignored and only created when publishing

**Comment by ryw** [comment]
@schnie can you look at this?

**Comment by schnie** [comment]
@merlinpatt it's been a while since I've worked on this but `client.js` and `server.js` reference the files in `dist`. Either solution works for me. If you send a PR we can merge it in!
