### ISSUE TITLE
Export Analytics so people can manually send events too

### ISSUE THREAD

**Issue by ryw** [astronomerio/meteor-astronomer#4]
Analytics.track isn't available.

**Comment by iDoMeteor** [comment]
https://github.com/astronomerio/meteor-astronomer/issues/2#issuecomment-117273672

**Comment by schnie** [comment]
analytics is a global object so should be available anywhere.  It's also lower case, so I think this one can be closed.

**Comment by ryw** [comment]
Agree - updated docs.
