### ISSUE TITLE
Eliminate babel dependency

### ISSUE THREAD

**Issue by ryw** [astronomerio/meteor-astronomer#7]
Adding Astronomer to Prowd.io breaks Prowd — some server methods are erroring (that are using an external promises library). This is unrelated to Astronomer, except for the fact that we brought Babel into the codebase.

Now that we know this can happen, I wonder if our package should compile and include a plain old javascript version, rather than the ES15/Babel version.

**Comment by schnie** [comment]
Aight, yea I'm guessing a the babel runtime polyfill thats auto included
with the meteor package has something to do with it.  I can move it to a
build system, just like the kinesis apps.  Precompile and distribute the
built version without including the polyfill, which we shouldn't need.

**Comment by ctaloi** [comment]
Hello,

I hit an issue on the beta version of mobile Safari due to the dependency on grigio:babel and thought you might be interested.  Details are https://github.com/grigio/meteor-babel/issues/30

Thanks -

**Comment by schnie** [comment]
Thanks! Should be fixed soon with our next release.
